# Generated by Django 3.2.5 on 2021-07-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('scope', models.CharField(choices=[('private', 'Creator can invite collaborators to this project.'), ('internal', 'Users in specific groups can list and may join this project.'), ('public', 'Authenticated users can list and may join this project.')], default='private', max_length=16)),
            ],
        ),
    ]
