# Generated by Django 3.2.5 on 2021-07-15 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0002_container'),
        ('project', '0002_userprojectbinding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectContainerBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.container')),
            ],
        ),
    ]
