# Generated by Django 3.2.5 on 2021-07-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectcontainerbinding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcontainerbinding',
            old_name='service',
            new_name='container',
        ),
    ]
