# Generated by Django 3.2.5 on 2021-07-22 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=500)),
                ('folder', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField()),
                ('expires_at', models.DateTimeField(null=True)),
                ('can_studentsubmit', models.BooleanField(default=True)),
                ('remove_collected', models.BooleanField(default=False)),
                ('is_massassignment', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='folder',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='coursecode',
            name='courseid',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='UserAssignmentBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(default=None, null=True)),
                ('valid_from', models.DateTimeField(default=None, null=True)),
                ('expires_at', models.DateTimeField(default=None, null=True)),
                ('state', models.CharField(choices=[('qed', 'Waiting for handout'), ('wip', 'Working on assignment'), ('sub', 'Submitted, waiting for corrections'), ('col', 'Collected, waiting for corrections'), ('cor', 'Assignment is being corrected'), ('rdy', 'Assignment is corrected')], default='qed', max_length=16)),
                ('submitted_at', models.DateTimeField(default=None, null=True)),
                ('corrected_at', models.DateTimeField(default=None, null=True)),
                ('score', models.FloatField(default=None, null=True)),
                ('feedback_text', models.TextField(default=None, null=True)),
                ('submit_count', models.IntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.assignment')),
                ('corrector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrector', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('course', 'name')},
        ),
    ]
