# Generated by Django 3.2.5 on 2021-07-22 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0002_auto_20210722_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassignmentbinding',
            name='corrected_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userassignmentbinding',
            name='corrector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrector', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userassignmentbinding',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userassignmentbinding',
            name='feedback_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userassignmentbinding',
            name='received_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userassignmentbinding',
            name='score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userassignmentbinding',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userassignmentbinding',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
