# Generated by Django 3.2.5 on 2021-07-23 18:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0004_auto_20210723_0749'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercoursebinding',
            unique_together={('user', 'course')},
        ),
    ]
