# Generated by Django 3.2.5 on 2021-07-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_alter_usercoursebinding_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassignmentbinding',
            name='correction_count',
            field=models.IntegerField(default=0),
        ),
    ]
