# Generated by Django 3.2.5 on 2021-07-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_userassignmentbinding_correction_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='is_massassignment',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
