# Generated by Django 3.2.5 on 2021-08-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_auto_20210724_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_can_delete_foreign_assignment',
            field=models.BooleanField(default=False),
        ),
    ]
