# Generated by Django 3.2.5 on 2021-08-05 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0006_alter_container_restart_reasons'),
        ('education', '0008_course_teacher_can_delete_foreign_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContainerBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.container')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.course')),
            ],
        ),
    ]
