# Generated by Django 3.2.5 on 2021-08-11 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_assignmentgroupbinding_group_usercoursegroupbinding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoursegroupbinding',
            name='usercoursebinding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.usercoursebinding', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='usercoursegroupbinding',
            unique_together=set(),
        ),
    ]
