# Generated by Django 3.2.5 on 2021-08-11 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_auto_20210811_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoursegroupbinding',
            name='usercoursebinding',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.usercoursebinding'),
        ),
    ]
