# Generated by Django 3.2.5 on 2021-08-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_alter_usercoursegroupbinding_usercoursebinding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignmentGroupBinding',
        ),
    ]
