# Generated by Django 3.2.5 on 2021-08-11 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_delete_assignmentgroupbinding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoursegroupbinding',
            name='usercoursebinding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.usercoursebinding'),
        ),
    ]
