# Generated by Django 3.2.5 on 2021-07-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('present', models.BooleanField(default=True)),
                ('imagetype', models.CharField(choices=[('projectimage', 'project image'), ('reportimage', 'report image'), ('apiimage', 'api image')], default='projectimage', max_length=32)),
                ('description', models.CharField(default='description missing', max_length=250)),
                ('dockerfile', models.TextField(max_length=4096)),
            ],
        ),
    ]
