# Generated by Django 3.2.5 on 2021-07-15 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('suffix', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('np', 'Not present.'), ('starting', 'Starting...'), ('run', 'Running fine.'), ('restart', 'Restart required'), ('oops', 'Error occured.'), ('stopping', 'Stopping...')], default='np', max_length=16)),
                ('restart_reasons', models.CharField(max_length=512, null=True)),
                ('last_message', models.CharField(max_length=512, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name', 'suffix')},
            },
        ),
    ]
