# Generated by Django 3.2.5 on 2021-07-16 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0002_container'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('port', models.IntegerField()),
                ('path', models.CharField(max_length=64, null=True)),
                ('path_open', models.CharField(max_length=64, null=True)),
                ('default', models.BooleanField(default=True)),
                ('token_as_argument', models.BooleanField(default=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.image')),
            ],
        ),
    ]
