# Generated by Django 3.2.5 on 2021-07-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0003_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvVarMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('valuemap', models.CharField(max_length=64)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.image')),
            ],
        ),
    ]
