# Generated by Django 3.2.5 on 2021-07-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0005_attachment_attachmentcontainerbinding_attachmentimagebinding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='restart_reasons',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
