# Generated by Django 3.2.5 on 2021-08-05 18:00

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0006_alter_container_restart_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^[a-z][a-z0-9]*\\Z'), 'Enter a valid container name containing only letters and numbers.', 'invalid')]),
        ),
    ]
