# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('docker_url', models.URLField()),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('ip', models.GenericIPAddressField()),
                ('command', models.TextField()),
                ('environment', models.TextField()),
                ('volumes', models.TextField()),
                ('ports', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('container_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hub.Container')),
                ('username', models.CharField(max_length=200)),
                ('port', models.IntegerField()),
                ('proxy_path', models.CharField(max_length=200)),
                ('external_url', models.CharField(max_length=200)),
            ],
            bases=('hub.container',),
        ),
    ]
