# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import kooplex.hub.models.modelbase


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('docker_host', models.CharField(max_length=200, null=True)),
                ('docker_port', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('network', models.CharField(max_length=200)),
                ('ip', models.GenericIPAddressField()),
                ('privileged', models.BooleanField()),
                ('command', models.TextField(null=True)),
                ('environment', models.TextField(null=True)),
                ('binds', models.TextField(null=True)),
                ('ports', models.TextField(null=True)),
                ('state', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'kooplex_hub_container',
            },
            bases=(models.Model, kooplex.hub.models.modelbase.ModelBase),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('notebook_path', models.CharField(max_length=200)),
                ('kernel_id', models.UUIDField()),
                ('kernel_name', models.CharField(max_length=15)),
                ('external_url', models.CharField(max_length=200)),
                ('is_forked', models.BooleanField()),
                ('project_id', models.IntegerField()),
                ('target_id', models.IntegerField()),
            ],
            options={
                'db_table': 'kooplex_hub_session',
            },
            bases=(models.Model, kooplex.hub.models.modelbase.ModelBase),
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('container_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hub.Container')),
                ('username', models.CharField(max_length=200)),
                ('port', models.IntegerField()),
                ('proxy_path', models.CharField(max_length=200)),
                ('external_url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'kooplex_hub_notebook',
            },
            bases=('hub.container',),
        ),
        migrations.AddField(
            model_name='session',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.Notebook'),
        ),
    ]
